import { Kumbh_Sans } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/toaster";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { PrimeReactProvider } from "primereact/api"

const font = Kumbh_Sans({ 
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <PrimeReactProvider>
          <body className={font.className}>
            {children}
            <Toaster />
          </body>
        </PrimeReactProvider>
      </html>
    </SessionProvider>
  );
}
